#ifndef CXI_DEFAULT_COUNTERS_H
#define CXI_DEFAULT_COUNTERS_H
static const char *const cxi_default_counters[] = {
    "pct_accel_close",          "pct_bad_seq_nacks",
    "pct_clear_close_drop",     "pct_clear_sent",
    "pct_close_rsp_drops",      "pct_close_sent",
    "pct_clr_cls_stalls",       "pct_cls_req_bad_seqno_drops",
    "pct_cls_req_miss_tct",     "pct_conn_sct_open",
    "pct_conn_tct_open",        "pct_err_no_matching_mst",
    "pct_err_no_matching_trs",  "pct_eth_packets",
    "pct_mem_cor_err_cntr",     "pct_mem_ucor_err_cntr",
    "pct_mst_hit_on_som",       "pct_no_matching_tct",
    "pct_no_mst_nacks",         "pct_no_tct_nacks",
    "pct_no_trs_nacks",         "pct_optip_packets",
    "pct_pct_cq_notifications", "pct_pct_cq_stalls",
    "pct_pct_ee_events",        "pct_pct_ee_stalls",
    "pct_pct_hni_flits",        "pct_pct_hni_stalls",
    "pct_pct_mst_cmd0",         "pct_pct_mst_cmd1",
    "pct_pct_mst_stalls0",      "pct_pct_mst_stalls1",
    "pct_ptls_response",        "pct_req_blocked_clearing",
    "pct_req_blocked_closing",  "pct_req_blocked_retry",
    "pct_req_no_response",      "pct_req_ordered",
    "pct_req_src_error",        "pct_req_tct_tmout_drops",
    "pct_req_unordered",        "pct_resource_busy",
    "pct_responses_received",   "pct_retry_mst_get",
    "pct_retry_srb_requests",   "pct_retry_trs_put",
    "pct_rsp_dropped_cls_try",  "pct_rsp_dropped_inactive",
    "pct_rsp_dropped_timeout",  "pct_rsp_dropped_try",
    "pct_rsp_err_rcvd",         "pct_sct_stall_state",
    "pct_sct_timeouts",         "pct_spt_timeouts",
    "pct_tct_timeouts",         "pct_tgt_cls_abort",
    "pct_trs_hit_on_req",       "pct_trs_replay_pend_drops",
    "pct_trs_rsp_nack_drops",   "rh:nacks",
    "rh:spt_timeouts",          "rh:sct_timeouts",
    "rh:nack_no_matching_conn", "rh:nack_no_target_mst",
    "rh:nack_resource_busy",    "rh:nack_sequence_error",
    "rh:nack_no_target_conn",   "rh:nack_no_target_trs",
    "rh:nack_trs_pend_rsp",     NULL /* sentinel */
};

#endif // CXI_DEFAULT_COUNTERS_H
