#!/usr/bin/env ruby

# Cannot use require_relative as iprof is not a rb file
# Load MPITopo and related helpers
load(File.join(__dir__, 'iprof'))

require 'open3'
require 'fileutils'
require 'securerandom'
require 'etc'
require 'socket'

FOLDER_JOBID = File.join('.thapi_lock', MPITopo.job_id)
SHARED_LOCAL_FILESYSTEM = File.join('/', 'dev', 'shm', Etc.getlogin, FOLDER_JOBID)
SHARED_GLOBAL_FILESYSTEM = File.join(env_fetch_first('THAPI_SHARED_PATH', 'HOME'), FOLDER_JOBID)

def count_file(folder)
  # \ls to avoid alias. Counter `.` and `..`, so remove them
  #  Will return -2 for a empty directory
  stdout_str = Open3.capture3("\\ls -afq #{folder}").first
  stdout_str.lines.size - 2
end

def init_global_barrier
  return unless MPITopo.local_master?

  f = File.join(SHARED_GLOBAL_FILESYSTEM, MPITopo.rank_id.to_s)
  FileUtils.mkdir_p(f)
  f
end

def global_barrier(f)
  return unless MPITopo.local_master?

  # Block until all the process have removed their sentinel,
  #    then master will clean the folder to be nice to the user
  #
  # Note that `MPITopo.master` can see the folder empty, and hence remove it
  #   at the same time as others threads sleep. They will wake up
  #   and see a deleted folder.
  # Fortunately `count_file` will return -2 for a non exciting folder
  #   hence we test for > 0 and not `!= 0`
  FileUtils.rm_rf(f)
  busy_wait_until { count_file(SHARED_GLOBAL_FILESYSTEM) <= 0 }
  FileUtils.rm_rf(SHARED_GLOBAL_FILESYSTEM) if MPITopo.master?
end

def local_barrier(name)
  folder = File.join(SHARED_LOCAL_FILESYSTEM, name)
  FileUtils.mkdir_p(File.join(folder, MPITopo.local_rank_id.to_s))
  busy_wait_until { count_file(folder) == MPITopo.local_size }
end

msg = nil
sock = UNIXSocket.for_fd(ARGV[0].to_i)
global_handle = init_global_barrier
local_barrier_count = 0

# We cannot delete SHARED_LOCAL_FILESYSTEM on FINISH: some rank can exit
# global_barrier (hence reach FINISH) while others are still in
# local_barrier. Removing SHARED_LOCAL_FILESYSTEM would deadlock them.
# One fix: have all ranks busy_wait_until in global_barrier so we
# know local_barrier is done — but given FS performance, we skip it.
until msg == SyncDaemon::MSG_FINISH
  msg, = sock.recvmsg(64)
  raise 'sync_daemon_fs: parent closed socket without sending FINISH' if msg.empty?

  case msg
  when SyncDaemon::MSG_INIT then nil
  when SyncDaemon::MSG_LOCAL_BARRIER
    local_barrier(local_barrier_count.to_s)
    local_barrier_count += 1
  when SyncDaemon::MSG_GLOBAL_BARRIER then global_barrier(global_handle)
  when SyncDaemon::MSG_FINISH         then nil
  else
    warn("sync_daemon_fs: unknown message '#{msg}'")
    exit(1)
  end

  sock.sendmsg(SyncDaemon::MSG_READY)
end

sock.close
