name: 'Setup Thapi Environment'
runs:
  using: "composite"
  steps:

    - name: Install APT Dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: gcc g++ ruby ruby-dev elfutils libelf-dev libpopt-dev libdw-dev libprotobuf-dev protobuf-compiler valgrind libglib2.0-dev libnuma-dev

    - name: Install Ruby Dependencies
      shell: bash
      run: sudo gem install cast-to-yaml nokogiri babeltrace2 opencl_ruby_ffi metababel

    - name: Set PKG_CONFIG
      shell: bash
      run: |
        echo "PKG_CONFIG_PATH=$HOME/efficios_dep/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

    - uses: actions/cache@v4
      id: efficios_dep
      with:
        path: ~/efficios_dep/
        key: ${{ runner.os }}-build-cache-efficios_dep

    - name: Build userspace-rcu
      shell: bash
      if: steps.efficios_dep.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/urcu/userspace-rcu -b v0.15.3
        cd userspace-rcu
        ./bootstrap
        ./configure --prefix=$HOME/efficios_dep/
        make -j$(nproc)
        make install

    - name: Build lttng-ust
      shell: bash
      if: steps.efficios_dep.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/lttng/lttng-ust -b v2.14.0
        cd lttng-ust
        wget https://raw.githubusercontent.com/argonne-lcf/THAPI-spack/a57eb4fa1b2b8621bb0e83a6ec25e48e3a761d15/packages/lttng-ust/55cca69.diff
        patch -p1 < 55cca69.diff
        ./bootstrap
        ./configure --disable-man-pages --prefix=$HOME/efficios_dep/
        make -j$(nproc)
        make install

    - name: Build lttng-tools
      shell: bash
      if: steps.efficios_dep.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/argonne-lcf/lttng-tools.git -b anl-ms3-v2.14.0
        cd lttng-tools
        ./bootstrap
        ./configure --disable-man-pages --disable-bin-lttng-crash --prefix=$HOME/efficios_dep
        make -j$(nproc)
        make install
        #Todo, this will need to be added in the spack repo as a patch
        echo "#!/usr/bin/env python"| cat - dirwatch.py > $HOME/efficios_dep/bin/dirwatch.py
        chmod 755 $HOME/efficios_dep/bin/dirwatch.py

    - name: Build babeltrace
      shell: bash
      if: steps.efficios_dep.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/efficios/babeltrace.git -b v2.1.1
        cd babeltrace
        wget https://raw.githubusercontent.com/argonne-lcf/THAPI-spack/ddc9a12a498331a7c312941df0d4e7078d03ae93/packages/babeltrace2/0001-Prevent-null-character-from-stopping-string-decoding.patch
        patch -p1 < 0001-Prevent-null-character-from-stopping-string-decoding.patch
        ./bootstrap
        ./configure --disable-man-pages --prefix=$HOME/efficios_dep
        make -j$(nproc)
        make install

    - name: Set Efficios environment variables
      shell: bash
      run: |
        echo "$HOME/efficios_dep/bin" >> $GITHUB_PATH
        echo "CPATH=$HOME/efficios_dep/include:$CPATH" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$HOME/efficios_dep/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "LIBRARY_PATH=$HOME/efficios_dep/lib:$LIBRARY_PATH" >> $GITHUB_ENV
