name: 'Setup Thapi Environment'
runs:
  using: "composite"
  steps:
    - name: Set Efficios environment variables
      shell: bash
      run: |
        echo "$HOME/efficios_dep/bin" >> $GITHUB_PATH
        echo "PKG_CONFIG_PATH=$HOME/efficios_dep/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
        echo "CPATH=$HOME/efficios_dep/include:$CPATH" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$HOME/efficios_dep/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "LIBRARY_PATH=$HOME/efficios_dep/lib:$LIBRARY_PATH" >> $GITHUB_ENV
