name: Presubmit
on: [push, pull_request]

jobs:
  pre_job:
    runs-on: ubuntu-24.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["**/README.md"]'
          do_not_skip: '["pull_request"]'


  build-and-check:
    needs: [pre_job]
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Build and Check ubuntu-24.04
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        config-option: ["", "--enable-clang-parser"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-thapi
      - name: Install dependencies for --enable-clang-parser
        if: matrix.config-option == '--enable-clang-parser'
        run: pip install git+https://github.com/TApplencourt/h2yaml
      - name: Make check
        run: |
          ./autogen.sh
          mkdir -p build
          cd build
          ../configure
          CC=gcc make -j
          make check
        env:
          THAPI_VALGRIND: 1
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: build-and-check-${{ matrix.config-option }}
          path: |
            build/**/*.log
            build/config.log
            build/**/tests/*.log

  install-with-mpi:
    needs: [pre_job]
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Install with MPI daemon support
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: mpi4py/setup-mpi@v1
        with:
          mpi: intelmpi
      - uses: ./.github/actions/setup-thapi
      - name: Make Install
        run: |
          ./autogen.sh
          mkdir -p build
          cd build
          ../configure --prefix=`pwd`/ici
          make -j install
      - name: Tar THAPI # https://github.com/actions/download-artifact?tab=readme-ov-file#permission-loss
        run: tar -cvf thapi.tar ./build/ici/
      - uses: actions/upload-artifact@v4
        with:
          name: thapi-bin
          path: thapi.tar

  integration-tests:
    needs: [pre_job, install-with-mpi]
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Integration ${{ matrix.bats_file }} ${{matrix.thapi_sync_daemon }}
    runs-on: ubuntu-24.04
    env:
      THAPI_TEST_BIN: clinfo
      THAPI_BIN_DIR: ./build/ici/bin
    steps:
      - uses: actions/checkout@v4
      - uses: mpi4py/setup-mpi@v1
        with:
          mpi: intelmpi
      - uses: actions/download-artifact@v4
        with:
          name: thapi-bin
      - name: Untar THAPI
        run: tar -xvf thapi.tar
      - uses: ./.github/actions/setup-thapi
      - run: |
          sudo apt install -y bats coreutils libpocl2 clinfo
      - name: Integration test
        run: |
          bats integration_tests/

  build-in-tree-and-check:
    needs: [pre_job]
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Build in Tree ubuntu-24.04
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-thapi
      - name: Make check
        run: |
          ./autogen.sh
          ./configure
          make -j
          make check
        env:
          THAPI_VALGRIND: 1
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: build-in-tree
          path: |
            ./**/*.log
            ./config.log
            ./**/tests/*.log

  distcheck:
    needs: [pre_job]
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Distcheck ubuntu-24.04
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-thapi
      - name: Make distcheck
        run: |
          ./autogen.sh
          mkdir -p build
          cd build
          ../configure
          make -j distcheck
        env:
          THAPI_VALGRIND: 1

  dist-check:
    needs: [pre_job]
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Dist and Check ubuntu-24.04
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-thapi
      - name: Make dist
        run: |
          ./autogen.sh
          mkdir -p build
          cd build
          ../configure
          make dist
      - name: Extract
        run: tar -xzvf thapi-*
        working-directory: build
      - name: Make Check
        run: |
          cd $(find . -type d -name "thapi-*")
          mkdir -p build
          cd build
          ../configure
          make -j check
        working-directory: build
        env:
          THAPI_VALGRIND: 1
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: dist-check
          path: |
            build/**/*.log
            build/config.log
            build/**/tests/*.log

  check-same-generated-file:
    needs: [pre_job]
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-thapi
      - run: pip install pyyaml pytest pytest-icdiff
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: base_branch

      # Configure and build target branch files
      - name: Configure target branch
        working-directory: base_branch
        run: |
          ./autogen.sh
          mkdir -p build
          cd build
          ../configure
      - name: Build target branch files
        working-directory: base_branch/build
        run: |
          make -C mpi tracer_mpi.c mpi_library.rb
          make -C omp tracer_ompt.c omp_library.rb
          make -C hip tracer_hip.c hip_library.rb
          make -C cuda tracer_cuda.c cuda_library.rb
          make -C cuda tracer_cudart.c
          make -C ze tracer_ze.c ze_library.rb
      # Checkout PR branch into a different directory
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr_branch
      # Configure and build PR branch files
      - name: Configure PR branch
        working-directory: pr_branch
        run: |
          ./autogen.sh
          mkdir -p build
          cd build
          ../configure
      - name: Build PR branch files
        working-directory: pr_branch/build
        run: |
          make -C mpi tracer_mpi.c mpi_library.rb
          make -C omp tracer_ompt.c omp_library.rb
          make -C hip tracer_hip.c hip_library.rb
          make -C cuda tracer_cuda.c cuda_library.rb
          make -C cuda tracer_cudart.c
          make -C ze tracer_ze.c ze_library.rb
      # Run comparison script
      - name: Compare files
        run: |
          THAPI_REF="base_branch/build" THAPI_NEW="pr_branch/build" pytest -vv pr_branch/utils/test_compare_generated_file.py
