name: shfmt
on:
  push:
  pull_request:
    branches:
      - main
      - devel
jobs:
  shfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run shfmt checker
        uses: reviewdog/action-shfmt@v1.0.4
        with:
          level: 'warning'
          fail_on_error: 'true'
          shfmt_flags: '-i 2 -ci -ln bats'
