name: shfmt
on:
  push:
  pull_request:
    branches:
      - main
      - devel
jobs:
  shfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install shfmt
        run: |
          curl -sS https://webi.sh/shfmt | sh
      - name: Run shfmt check
        run: |
          shfmt -i 2 -ci -ln bats -d .
